version: '3.8'
services:
  django:
    container_name: django_backend
    image: python:3.11.1
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - db
    networks:
      - django-net

  db:
    container_name: django_db
    image: postgres
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    networks:
      - django-net

networks:
  django-net:
    driver: bridge